/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserDefinedIndexRouteImport } from './routes/user-defined/index'
import { Route as UserDefinedBlockTypeIndexRouteImport } from './routes/user-defined/$blockType/index'
import { Route as UserDefinedBlockTypeNewRouteImport } from './routes/user-defined/$blockType/new'
import { Route as UserDefinedBlockTypeEditRouteImport } from './routes/user-defined/$blockType/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDefinedIndexRoute = UserDefinedIndexRouteImport.update({
  id: '/user-defined/',
  path: '/user-defined/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDefinedBlockTypeIndexRoute =
  UserDefinedBlockTypeIndexRouteImport.update({
    id: '/user-defined/$blockType/',
    path: '/user-defined/$blockType/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserDefinedBlockTypeNewRoute = UserDefinedBlockTypeNewRouteImport.update({
  id: '/user-defined/$blockType/new',
  path: '/user-defined/$blockType/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDefinedBlockTypeEditRoute =
  UserDefinedBlockTypeEditRouteImport.update({
    id: '/user-defined/$blockType/edit',
    path: '/user-defined/$blockType/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user-defined': typeof UserDefinedIndexRoute
  '/user-defined/$blockType/edit': typeof UserDefinedBlockTypeEditRoute
  '/user-defined/$blockType/new': typeof UserDefinedBlockTypeNewRoute
  '/user-defined/$blockType': typeof UserDefinedBlockTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user-defined': typeof UserDefinedIndexRoute
  '/user-defined/$blockType/edit': typeof UserDefinedBlockTypeEditRoute
  '/user-defined/$blockType/new': typeof UserDefinedBlockTypeNewRoute
  '/user-defined/$blockType': typeof UserDefinedBlockTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user-defined/': typeof UserDefinedIndexRoute
  '/user-defined/$blockType/edit': typeof UserDefinedBlockTypeEditRoute
  '/user-defined/$blockType/new': typeof UserDefinedBlockTypeNewRoute
  '/user-defined/$blockType/': typeof UserDefinedBlockTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user-defined'
    | '/user-defined/$blockType/edit'
    | '/user-defined/$blockType/new'
    | '/user-defined/$blockType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user-defined'
    | '/user-defined/$blockType/edit'
    | '/user-defined/$blockType/new'
    | '/user-defined/$blockType'
  id:
    | '__root__'
    | '/'
    | '/user-defined/'
    | '/user-defined/$blockType/edit'
    | '/user-defined/$blockType/new'
    | '/user-defined/$blockType/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserDefinedIndexRoute: typeof UserDefinedIndexRoute
  UserDefinedBlockTypeEditRoute: typeof UserDefinedBlockTypeEditRoute
  UserDefinedBlockTypeNewRoute: typeof UserDefinedBlockTypeNewRoute
  UserDefinedBlockTypeIndexRoute: typeof UserDefinedBlockTypeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-defined/': {
      id: '/user-defined/'
      path: '/user-defined'
      fullPath: '/user-defined'
      preLoaderRoute: typeof UserDefinedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-defined/$blockType/': {
      id: '/user-defined/$blockType/'
      path: '/user-defined/$blockType'
      fullPath: '/user-defined/$blockType'
      preLoaderRoute: typeof UserDefinedBlockTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-defined/$blockType/new': {
      id: '/user-defined/$blockType/new'
      path: '/user-defined/$blockType/new'
      fullPath: '/user-defined/$blockType/new'
      preLoaderRoute: typeof UserDefinedBlockTypeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-defined/$blockType/edit': {
      id: '/user-defined/$blockType/edit'
      path: '/user-defined/$blockType/edit'
      fullPath: '/user-defined/$blockType/edit'
      preLoaderRoute: typeof UserDefinedBlockTypeEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserDefinedIndexRoute: UserDefinedIndexRoute,
  UserDefinedBlockTypeEditRoute: UserDefinedBlockTypeEditRoute,
  UserDefinedBlockTypeNewRoute: UserDefinedBlockTypeNewRoute,
  UserDefinedBlockTypeIndexRoute: UserDefinedBlockTypeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
