name: Automation Engine CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build and Test All Modules
        run: mvn -B clean verify

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: automation-engine-jars
          path: |
            automation-engine-core/target/*.jar
            automation-engine-templating/target/*.jar
            automation-engine-spring-starter/target/*.jar
            automation-engine-http/target/*.jar